### ISSUE TITLE
Consulta con error 500

### ISSUE THREAD

**Issue by mikeiwi** [Facturedo/query-ruc#1]
https://fact2-ruc.herokuapp.com/ruc/76.178.3602
Esta consulta me resulta en error.

**Comment by mikeiwi** [comment]
Por cierto, luego de ese error, hice una consulta correcta: https://fact2-ruc.herokuapp.com/ruc/20100047218
Pero la aplicación seguía respondiendo error 500. Los logs indicaban que la aplicación estaba en estado crashed. Luego de reiniciar el dyno, la consulta correcta funcionó.

**Comment by jsandovalc** [comment]
El error se daba porque la librería que usamos (ConsultaSunac) tiene una implementación que a mi parecer no es la mejor. Por defecto es un script para ejecutarse desde la linea de comandos y cuando se usa como una librería, importando la función, lo que uno hace es simular que a la función se le envían parámetros que son procesados por argparse y este, cuando se le envía un parámetro captura la excepción y levanta un SystemExit. 

Ese comportamiento es correcto para un programa de la cli pero no para una librería, ya que al levantar la excepción SystemExit hacía que la aplicación terminara. Hay que cambiar esa parte de la librería eventualmente pero por ahora estoy capturando la excepción y retornando 400 si el RUC enviado es inválido. Ya está en heroku.
